// +build bindata

// bindata_serving.go is only compiled into your app if the bindata
// build tag is present.
//
// This file includes functions that wrap the functions generated by
// the go-bindata tool.
//
// Calling "abcweb build --bundle" will include this bindata build tag
// and also generate you a bindata.go file containing your asset files.

package serving

import (
	"bytes"
	"os"
)

type assetFile struct {
	*bytes.Reader
}

func (assetFile) Close() error {
	return nil
}

func Open(name string) (ReadSeekCloser, error) {
	var file assetFile

	b, err := Asset(name)
	if err != nil {
		return file, nil
	}

	file.Reader = bytes.NewReader(b)
	return file, nil
}

func ReadFile(name string) ([]byte, error) {
	return Asset(name)
}

func Stat(name string) (os.FileInfo, error) {
	return AssetInfo(name)
}
