package serving

// The serving package includes files related to the serving of assets
// from either disk or the go-bindata generated file.
//
// The serving package conditionally compiles methods for handling assets
// depending on whether the bindata go build tag is present or not.
//
// For example, if you compile without the "bindata" tag then your
// calls to Open and Stat will pipe out to os.Stat and os.ReadFile,
// but if you DO compile with the "bindata" tag your calls will
// pipe out to the Asset and AssetInfo functions generated by go-bindata.

import "io"

type ReadSeekCloser interface {
	io.Reader
	io.Seeker
	io.Closer
}
